# Generated by Django 5.0.6 on 2024-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
