# Generated by Django 5.0.6 on 2024-06-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='media/profilepic.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
